FROM node:22-alpine AS build
WORKDIR /app
COPY frontend/package.json frontend/
COPY frontend ./frontend
WORKDIR /app/frontend
RUN npm install && npm run build
FROM nginx:alpine
COPY --from=build /app/frontend/dist /usr/share/nginx/html
