<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'
import PageHeader from '../components/PageHeader.vue'
import studyScene from '../assets/study-scene.jpeg'
const route=useRoute(),active=ref('导数'),joined=ref(false)
const nebula=computed(()=>route.params.feature==='nebula')
</script>
<template><section><PageHeader eyebrow="CONCEPT PREVIEW" :title="nebula?'思绪星云':'共学空间'" :subtitle="nebula?'把理解证据组织成可回看的知识地图':'选择一种陪伴方式，让学习不再孤单'"><span class="chip demo">概念演示 · 无网络请求</span></PageHeader>
  <template v-if="nebula"><div class="nebula card"><button v-for="(node,i) in ['平均变化率','瞬时变化率','导数','极限思想','切线斜率']" :key="node" :class="[`node-${i}`,{active:active===node}]" @click="active=node">{{node}}<small>{{i===2?'核心节点':'学习证据'}}</small></button></div><article class="card panel insight"><span class="chip success">当前节点</span><h2>{{active}}</h2><p>该知识图谱为 Figma 概念演示。节点点击仅改变当前页面状态，不代表后端已经生成或保存知识图谱。</p><div class="grid-2"><div class="notice success">掌握较好：变化率概念</div><div class="notice">建议复习：切线斜率</div></div></article></template>
  <template v-else><div class="companion-stage card" :style="{ backgroundImage: `linear-gradient(155deg, rgba(255,255,255,.82), rgba(228,249,252,.82), rgba(238,233,255,.82)), url(${studyScene})` }"><div class="orb">FLOW<br/>TUTOR</div><h2>{{joined?'已进入安静共学':'今天想和谁一起学？'}}</h2><p>{{joined?'当前状态只在页面内演示，不会建立真实音视频连接。':'好友、视频与虚拟学伴均为概念功能。'}}</p><div class="grid-3"><button @click="joined=true"><b>♧</b><strong>好友共学</strong><small>彼此监督</small></button><button @click="joined=true"><b>▣</b><strong>视频共学</strong><small>共享进度</small></button><button @click="joined=true"><b>◉</b><strong>虚拟学伴</strong><small>安静陪伴</small></button></div><button class="btn btn-primary" @click="joined=!joined">{{joined?'退出概念会话':'进入概念会话 →'}}</button></div></template>
</section></template>
<style scoped>.nebula{position:relative;min-height:480px;overflow:hidden;background:radial-gradient(circle at center,#e9e5ff,#15245a 70%,#0d1740)}.nebula:before{content:"";position:absolute;inset:0;background-image:radial-gradient(#fff 1px,transparent 1px);background-size:36px 36px;opacity:.35}.nebula button{position:absolute;border:1px solid rgba(255,255,255,.4);border-radius:18px;padding:12px 18px;background:rgba(255,255,255,.15);backdrop-filter:blur(8px);color:white;display:grid;gap:3px}.nebula button small{opacity:.7}.nebula button.active{background:linear-gradient(120deg,var(--cyan),var(--violet));box-shadow:0 0 30px rgba(84,221,233,.6)}.node-0{left:9%;top:18%}.node-1{right:9%;top:15%}.node-2{left:42%;top:40%}.node-3{left:13%;bottom:17%}.node-4{right:10%;bottom:16%}.insight{margin-top:18px}.insight p{color:var(--muted);line-height:1.7}.companion-stage{text-align:center;padding:55px 35px;background-size:cover;background-position:center}.companion-stage>.orb{width:150px;height:150px;margin:auto;display:grid;place-content:center;border-radius:50%;color:white;font-size:12px;line-height:1.6;background:radial-gradient(circle at 35% 25%,white,#54dde9 22%,#7665ec 62%,#342671);box-shadow:0 0 70px rgba(84,221,233,.5)}.companion-stage h2{margin:30px 0 8px}.companion-stage p{color:var(--muted)}.companion-stage .grid-3{margin:28px 0}.companion-stage .grid-3 button{border:1px solid white;border-radius:22px;background:rgba(255,255,255,.7);padding:25px;display:grid;gap:8px;color:var(--text)}.companion-stage b{font-size:26px;color:var(--brand)}@media(max-width:650px){.nebula{min-height:430px}.nebula button{padding:9px;font-size:11px}.companion-stage .grid-3{grid-template-columns:1fr}.companion-stage{padding:35px 18px}}
</style>
