<script setup lang="ts">
import { onMounted, ref } from 'vue'
import PageHeader from '../components/PageHeader.vue'
import { getMetrics } from '../services/evaluation'
import type { MetricsResponse } from '../types'
const metrics=ref<MetricsResponse|null>(null),added=ref(false)
const days=[28,29,30,...Array.from({length:31},(_,i)=>i+1),1]
onMounted(async()=>{try{metrics.value=await getMetrics()}catch{/* 静态复盘仍可展示 */}})
</script>
<template><section><PageHeader eyebrow="WEEKLY REVIEW" title="学习复盘" subtitle="回看掌握，决定下一步"><span class="chip demo">部分演示数据</span></PageHeader>
  <div class="profile-card card"><div class="avatar">杨</div><div><h2>小杨同学</h2><p>今天也在稳步前进</p><span class="chip">连续学习 12 天</span></div><div class="profile-number"><strong>14.2h</strong><small>本周学习</small></div></div>
  <div class="review-grid"><article class="calendar card panel"><div class="row between"><h2>学习日历</h2><span class="chip">2026 年 7 月</span></div><div class="week"><span v-for="w in '日一二三四五六'" :key="w">{{ w }}</span></div><div class="days"><button v-for="(day,i) in days" :key="i" :class="{active:day===21,learned:[5,8,10,14,17,19,21,24].includes(day)}">{{ day }}</button></div></article><article class="card panel stats"><h2>选中日期 · 7 月 21 日</h2><div class="grid-3"><div class="metric"><strong>3h20m</strong><small>有效学习</small></div><div class="metric"><strong>86%</strong><small>专注率</small></div><div class="metric"><strong>4 项</strong><small>完成任务</small></div></div><h3>学习时段</h3><div class="bars"><i style="height:45%"><span>45m</span></i><i style="height:70%"><span>70m</span></i><i style="height:40%"><span>40m</span></i><i style="height:85%"><span>85m</span></i></div><div class="bar-labels"><span>高数</span><span>数据结构</span><span>英语</span><span>课程设计</span></div></article></div>
  <div class="section-title"><h2>学习进度</h2><span class="muted small">本周目标</span></div><div class="progress card panel"><div class="row between"><strong>14.2 / 18 小时</strong><span>79%</span></div><div class="track"><i/></div><p>已经过 11 / 15 个任务 · 计划状态稳定</p></div>
  <div class="grid-2 review-bottom"><article class="card panel"><div class="row between"><h2>掌握分布</h2><span class="small muted">演示数据</span></div><div v-for="item in [{n:'迁移完成',v:62},{n:'理解完成',v:81},{n:'普通完成',v:94}]" :key="item.n" class="mastery"><div class="row between"><span>{{ item.n }}</span><strong>{{ item.v }}%</strong></div><div class="track"><i :style="{width:item.v+'%'}"/></div></div><p class="muted small">完成 ≠ 掌握，状态来自复述与迁移证据。</p></article><article class="health card panel"><h2>计划健康</h2><div class="health-ring"><strong>79%</strong><small>稳定</small></div><span class="chip">真实运行 {{ metrics?.agent_runs ?? '—' }} 次</span></article></div>
  <article class="suggestion card panel"><span class="agent-mark">✦</span><div><p class="eyebrow">薄弱点与复习建议 · 演示数据</p><h3>明天先复述二叉树三种遍历</h3><p>依据：迁移题回答缺少边界条件 · 预计 15 分钟</p></div><button class="btn btn-primary" @click="added=true">{{added?'已加入页面计划':'加入明日计划'}}</button></article>
</section></template>
<style scoped>.profile-card{padding:22px;display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:16px;background:linear-gradient(120deg,#d4efff,#d6d5ff)}.avatar{width:58px;height:58px;border-radius:50%;display:grid;place-items:center;background:white;color:var(--brand);font-weight:900}.profile-card h2{margin:0 0 4px}.profile-card p{margin:0 0 10px;color:var(--muted)}.profile-number{display:grid;text-align:right}.profile-number strong{font-size:24px}.profile-number small{color:var(--muted)}.review-grid{display:grid;grid-template-columns:1fr 1.3fr;gap:16px;margin-top:18px}.calendar h2,.stats h2{margin:0}.week,.days{display:grid;grid-template-columns:repeat(7,1fr);gap:6px;text-align:center;margin-top:14px}.week{font-size:11px;color:var(--muted)}.days button{border:0;background:transparent;padding:8px;border-radius:10px;color:var(--muted)}.days button.learned{background:#eef2ff;color:var(--brand)}.days button.active{background:var(--brand);color:white}.stats .grid-3{margin:18px 0}.stats h3{font-size:14px}.bars{height:145px;display:flex;align-items:end;justify-content:space-around;border-bottom:1px solid var(--border);padding:0 12px}.bars i{position:relative;width:26px;border-radius:10px 10px 0 0;background:linear-gradient(#7d66f6,#30c9db)}.bars i span{position:absolute;top:-18px;font-size:9px;color:var(--brand)}.bar-labels{display:flex;justify-content:space-around;font-size:10px;color:var(--muted);padding-top:7px}.track{height:8px;border-radius:99px;background:#e9edf7;overflow:hidden}.track i{display:block;height:100%;width:79%;background:linear-gradient(90deg,var(--cyan),var(--brand),var(--violet))}.progress p{margin:10px 0 0;color:var(--muted);font-size:12px}.mastery{display:grid;gap:6px;margin:16px 0}.mastery .track i{background:linear-gradient(90deg,var(--cyan),var(--violet))}.health{text-align:center}.health-ring{width:120px;height:120px;margin:20px auto;display:grid;place-content:center;border-radius:50%;background:radial-gradient(circle,#fff 56%,transparent 58%),conic-gradient(var(--brand) 79%,#e7eaff 0)}.health-ring strong{font-size:25px}.health-ring small{color:var(--muted)}.suggestion{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:15px;margin-top:18px}.agent-mark{width:44px;height:44px;display:grid;place-items:center;border-radius:15px;background:linear-gradient(135deg,var(--cyan),var(--violet));color:white}.suggestion h3{margin:3px 0}.suggestion p{margin:0;color:var(--muted);font-size:12px}@media(max-width:800px){.review-grid{grid-template-columns:1fr}}@media(max-width:620px){.profile-card,.suggestion{grid-template-columns:auto 1fr}.profile-number,.suggestion button{grid-column:2;text-align:left}.review-bottom{grid-template-columns:1fr}.stats .grid-3{grid-template-columns:repeat(3,1fr)}.stats .metric{padding:9px}.stats .metric strong{font-size:16px}}
</style>
